Updating readme to highlight pysocks dependency for Python 3.6
sarah-story/shelterbot pull request #11
Opened 2018-01-14 21:38 UTC by MCBoarder289

2018-01-14 22:30 UTC, seanstory submitted a review, later dismissed

2018-01-15 02:48 UTC, sarah-story requested changes
Other than my one comment, I think this looks good! We can put a ticket in the backlog for adding error handling around the api calls - always a good idea to plan for failures when you're working with an external service.

2018-01-15 02:48 UTC, sarah-story commented on shelterbot/handlers/weather.py
> +"""
Can you move this string/comment somewhere else? Maybe the README?

2018-01-15 03:07 UTC, sarah-story approved these changes
Looks great! Feel free to merge it.

2018-01-15 03:15 UTC, merged